### ISSUE TITLE
需要一个支持

### ISSUE THREAD

**Issue by Fzyfeng** [code-farmer-i/el-table-footer#1]
大佬好，
    最近用你的这个footer非常方便，希望能加一个可以把footer fixed在页面底部的配置；这种情况是为了解决在分页条数过多的情况下不方便看合计，每次都要拖动到最下面很不方便，固定在底部就会很方便查看

**Comment by code-farmer-i** [comment]
建议你给表格定高，或者给一个max-height

**Comment by Fzyfeng** [comment]
oh yes 是的给加一个高度可以完美解决，但是这个高度不能自适应容器的高度，我去自定义计算下

**Comment by code-farmer-i** [comment]
老哥，给个star呗
