### ISSUE TITLE
请教一些问题

### ISSUE THREAD

**Issue by 543a** [code-farmer-i/el-table-footer#10]
嗨，您好，可以请教您一些问题吗？合计部分的合并单元格，您有专门写的方法吗？才疏学浅有些看不太懂您的代码，我是前端初学者，很期待您的回复

**Comment by code-farmer-i** [comment]
不支持合并单元格- -

**Comment by 543a** [comment]
![image](https://user-images.githubusercontent.com/49392737/84342546-642a4980-abd8-11ea-951d-3c2bb9bec2d4.png)
可以稍微讲一下这是什么意思吗？谢谢

**Comment by 543a** [comment]
<tr>
            {
              this.columns.map((column, cellIndex) => <td
                key={cellIndex}
                colspan={ column.colSpan }
                rowspan={ column.rowSpan }
                class={ this.getRowClasses(column, cellIndex) }>
                <div class={ ['cell', column.labelClassName] }>
                  {
                    sums[cellIndex]
                  }
                </div>
              </td>)
            }

**Comment by 543a** [comment]
this.columns.map((column, cellIndex) => <td
                key={cellIndex}
                colspan={ column.colSpan }
                rowspan={ column.rowSpan }
                class={ this.getRowClasses(column, cellIndex) }>
                <div class={ ['cell', column.labelClassName] }>
                  {
                    sums[cellIndex]
                  }

**Comment by code-farmer-i** [comment]
你这是element的代码吧？

**Comment by 543a** [comment]
table-footer.js  是element的组件文件呀  ？

**Comment by code-farmer-i** [comment]
嗯 是的

**Comment by 543a** [comment]
谢谢
