### ISSUE TITLE
想问一下 滚动条的问题

### ISSUE THREAD

**Issue by Fzyfeng** [code-farmer-i/el-table-footer#2]
![image](https://user-images.githubusercontent.com/23629370/60149555-aad83580-9807-11e9-922d-6265cb2ec093.png)
我自己用的话出现的滚动条是在固定列的下方，而项目主你的示例是在固定列的上方。现在我遇到了如果滚动到最下面就会出现错位的情况，如图。想问一下大佬这种滚动条设置在固定列上方是怎么实现的

**Comment by Fzyfeng** [comment]
我发现原因了，是因为数据在列表加载后载入才会这种情况

**Comment by code-farmer-i** [comment]
没发现有这个问题。。

**Comment by Fzyfeng** [comment]
哭，诡异的问题，滚动最后一下错位，我去好好研究下，不是拟组件的问题

**Comment by code-farmer-i** [comment]
你是用了max-height吗

**Comment by Fzyfeng** [comment]
![image](https://user-images.githubusercontent.com/23629370/60157434-52159680-9821-11e9-95b2-469ae8ff3077.png)
![image](https://user-images.githubusercontent.com/23629370/60157458-622d7600-9821-11e9-8788-c454fba4be6e.png)
木有我用的是动态计算的height，所以高度是没问题的，我又看了下即使是数据和表头一起传进去也是会错位。
![image](https://user-images.githubusercontent.com/23629370/60157792-2941d100-9822-11e9-9e4e-5a04f72b64ef.png)

**Comment by code-farmer-i** [comment]
你可以试试 el-table 的doLayout方法

**Comment by Fzyfeng** [comment]
这个方法我也看见了 正在想怎么调用。。。

**Comment by Fzyfeng** [comment]
试了不行

**Comment by Fzyfeng** [comment]
我吐槽下 试了半天终于找到了原因 全局的-webkit-scrollbar样式覆盖导致的，之后试了无数种方法，最后只能把全局的覆盖去掉，哪里用到再给加上，不然怎么搞都会导致这个table错位
