### ISSUE TITLE
Dont update the prop data when input changes

### ISSUE THREAD

**Issue by robertonav20** [code-farmer-i/el-table-footer#5]
Hi,
i have a problem with el-table-footer.
I use prop "data" for the component but when i change the data el-table-footer dont rerender.

Example
`
<el-table ref="employeeTable" .......></el-table>
<el-table-footer ref="tableFooterEmp"  :data="sumsEmp"></el-table-footer>
`
Template

Data
`
sumsEmp: [
 {
   label: 'Tot.',
   data: {
     hoursAvailble: 0
   }
 }
]
`
Method
`
loadTableFooter(tableFooter, table) {
  tableFooter.init(table)
}
`
How can i fix the issue?

**Comment by robertonav20** [comment]
I try to make an example of the problem with codePen, but i can't import ElTableFooter because dont exist a dist version online.

https://codepen.io/robertonav20/pen/MWWyXRa

**Comment by code-farmer-i** [comment]
Are you sure sumsEmp is reactivity?

**Comment by robertonav20** [comment]
Yes, of course!

I change the template into table-footer.vue and the prop "data" is old.

![image](https://user-images.githubusercontent.com/6991920/66820262-a1064980-ef40-11e9-90fc-c8c2fa06d4e3.png)

**Comment by robertonav20** [comment]
![image](https://user-images.githubusercontent.com/6991920/66821636-0a875780-ef43-11e9-97e6-71982b5ea642.png)

**Comment by robertonav20** [comment]
I'm sorry.

I fix the problem, i will try explain it.
The sumsEmp init with this structure [:](sumsEmp: [ { label: 'Tot.', data: {} } ]) then i create the field hoursAvailable in "data", so dont exist the reactive getter/setter.

Thanks!

**Comment by code-farmer-i** [comment]
Never mind！
